<?xml version="1.0"?>
<package format="2">
  <name>leap_motion_noetic</name>
  <version>0.1.0</version>
  <description>ROS driver for the Leap Motion gesture sensor, based on the original 'leap_motion' package.</description>


  <maintainer email="37772537+Tisma09@users.noreply.github.com">Tismo</maintainer>

  <license>BSD</license>
  <url type="website">https://github.com/Tisma09/leap_motion_noetic/</url>
  <url type="repository">https://github.com/Tisma09/leap_motion_noetic/</url>
  <url type="bugtracker">https://github.com/Tisma09/leap_motion_noetic/</url>
  <author email="37772537+Tisma09@users.noreply.github.com">Tismo</author>

  <buildtool_depend>catkin</buildtool_depend>

  <!-- <depend>camera_calibration_parsers</depend> -->
  <!-- <depend>camera_info_manager</depend> -->
  <depend>geometry_msgs</depend>
  <depend>visualization_msgs</depend>
  <depend>roscpp</depend>
  <depend>rospack</depend> 
  <depend>std_msgs</depend>
  <depend>rospy</depend>

  <!-- <build_depend>message_generation</build_depend> -->
  <exec_depend>message_runtime</exec_depend>
  <exec_depend>leap_motion_msgs</exec_depend>
  
  <test_depend>rostest</test_depend>
  
  <export>
  </export>
</package>
